import { Schema, model, Document, Types } from "mongoose";
import { LeadRef, UserRef } from "./common";

export type TaskStatus = "OPEN" | "COMPLETED" | "CANCELLED";
export type TaskType =
  | "general"
  | "followup"
  | "call"
  | "email"
  | "whatsapp"
  | "meeting";

export interface ITask extends Document {
  title: string;
  description?: string;
  ownerUserId: any;
  createdByUserId: any;
  leadId?: any;
  accountId?: any;
  orgId?: Types.ObjectId | any;
  dueAt: Date;
  status: TaskStatus;
  type: TaskType;
  followupRuleId?: Types.ObjectId | any;
  isAutoGenerated?: boolean;
  completedAt?: Date | null;
  completedByUserId?: Types.ObjectId | any;
  outcome?: string | null;
  popupState?: {
    lastShownAt?: Date;
    dismissedAt?: Date;
    workflowFollowupMissedEmittedAt?: Date; // When we emitted lead.followup_missed for this task
  };
}

const taskSchema = new Schema<ITask>(
  {
    title: { type: String, required: true },
    description: String,
    ownerUserId: UserRef,
    createdByUserId: UserRef,
    leadId: LeadRef,
    accountId: {
      type: Schema.Types.ObjectId,
      ref: "Account",
      default: null,
      index: true,
    },
    orgId: { type: Schema.Types.ObjectId, required: false, default: null, index: true },
    dueAt: { type: Date, required: true, index: true },
    status: {
      type: String,
      enum: ["OPEN", "COMPLETED", "CANCELLED"],
      default: "OPEN",
      index: true,
    },
    type: {
      type: String,
      enum: ["general", "followup", "call", "email", "whatsapp", "meeting"],
      default: "general",
      index: true,
    },
    followupRuleId: {
      type: Schema.Types.ObjectId,
      ref: "FollowupRule",
      index: true,
    },
    isAutoGenerated: { type: Boolean, default: false },
    completedAt: { type: Date, default: null },
    completedByUserId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
    outcome: { type: String, default: null },
    popupState: {
      lastShownAt: Date,
      dismissedAt: Date,
      workflowFollowupMissedEmittedAt: { type: Date, default: null },
    },
  },
  { timestamps: true }
);

taskSchema.index({ ownerUserId: 1, status: 1, dueAt: 1 });
taskSchema.index({ leadId: 1, status: 1 });
taskSchema.index({ orgId: 1, dueAt: 1, status: 1 });
taskSchema.index({ dueAt: 1, status: 1, type: 1 });

export const TaskModel = model<ITask>("Task", taskSchema);



