import { useState, useEffect, useMemo } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { formGrid2 } from "@/lib/responsive";
import { Textarea } from "@/components/ui/textarea";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import {
  Task,
  updateTask,
  createTask,
  deleteTask,
} from "@/services/tasks";
import { listLeads, Lead, getLeadContactInfo } from "@/services/leads";
import {
  Calendar as CalendarIcon,
  Plus,
  Clock,
  CheckCircle2,
  Loader2,
  ExternalLink,
  X,
} from "lucide-react";
import { format, startOfMonth, endOfMonth, eachDayOfInterval, isSameDay, isToday } from "date-fns";
import {
  getWeekPlannerData,
  type WeekPlannerAccount,
  type WeekPlannerActivity,
  type WeekPlannerFollowUp,
  type WeekPlannerTask,
} from "@/services/weekPlanner";
import { formatContactActivityType } from "@/services/contactActivities";
import { ActivityWizard } from "@/components/activities/ActivityWizard";
import { listAccounts, type Account } from "@/services/accounts";

interface PersonalCalendarProps {
  userName?: string;
  backendUserId?: string;
  isAdmin?: boolean;
  permissions?: string[];
  onViewLead?: (leadId: string) => void;
  onViewAccount?: (accountId: string) => void;
}

type CalendarItem =
  | { kind: "activity"; date: Date; activity: WeekPlannerActivity }
  | { kind: "task"; date: Date; task: Task }
  | { kind: "account_followup"; date: Date; followUp: WeekPlannerFollowUp };

export const PersonalCalendar = ({
  userName,
  backendUserId,
  onViewLead,
  onViewAccount,
}: PersonalCalendarProps) => {
  const { toast } = useToast();
  const [tasks, setTasks] = useState<Task[]>([]);
  const [activities, setActivities] = useState<WeekPlannerActivity[]>([]);
  const [accountFollowUps, setAccountFollowUps] = useState<WeekPlannerFollowUp[]>([]);
  const [leads, setLeads] = useState<Lead[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [selectedDate, setSelectedDate] = useState<Date>(new Date());
  const [currentMonth, setCurrentMonth] = useState<Date>(new Date());
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [isCreating, setIsCreating] = useState(false);
  const [deleteTaskId, setDeleteTaskId] = useState<string | null>(null);
  const [plannerAccounts, setPlannerAccounts] = useState<WeekPlannerAccount[]>([]);
  const [mappedAccounts, setMappedAccounts] = useState<Account[]>([]);
  const [accountPickerOpen, setAccountPickerOpen] = useState(false);
  const [pickerAccountId, setPickerAccountId] = useState("");
  const [activityAccountId, setActivityAccountId] = useState<string | null>(null);
  const [activityWizardOpen, setActivityWizardOpen] = useState(false);
  const [activityInitialDate, setActivityInitialDate] = useState<Date | undefined>();
  const [newTask, setNewTask] = useState({
    title: "",
    description: "",
    leadId: "none",
    dueAt: "",
    dueTime: "",
  });

  useEffect(() => {
    void loadTasks();
    void loadLeads();
  }, [backendUserId, currentMonth]);

  useEffect(() => {
    listAccounts({ myAccounts: true })
      .then(setMappedAccounts)
      .catch(() => setMappedAccounts([]));
  }, []);

  const loadTasks = async () => {
    try {
      setIsLoading(true);
      const planner = await getWeekPlannerData(
        startOfMonth(currentMonth),
        endOfMonth(currentMonth)
      );
      setTasks(
        planner.tasks.map((task: WeekPlannerTask) => ({
          id: task._id,
          title: task.title,
          ownerUserId: backendUserId || "",
          leadId: task.leadId?._id,
          dueAt: task.dueAt,
          status: task.status as Task["status"],
          type: task.type as Task["type"],
          isAutoGenerated: false,
          lead: task.leadId
            ? {
                id: task.leadId._id,
                leadNumber: task.leadId.leadNumber || "",
                status: task.leadId.status || "",
              }
            : undefined,
          accountId: task.accountId?._id,
          account: task.accountId,
        })) as Task[]
      );
      setActivities(planner.activities);
      setAccountFollowUps(planner.followUps);
      setPlannerAccounts(planner.accounts ?? []);
    } catch (err) {
      toast({
        title: "Error",
        description: err instanceof Error ? err.message : "Failed to load calendar",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const loadLeads = async () => {
    try {
      const allLeads = await listLeads({ scope: "own" });
      setLeads(allLeads);
    } catch (err) {
      console.error("Failed to load leads:", err);
    }
  };

  const activityAccounts = useMemo(() => {
    const map = new Map<string, string>();
    for (const a of mappedAccounts) map.set(a.id, a.name);
    for (const a of plannerAccounts) map.set(a._id, a.name);
    return Array.from(map, ([id, name]) => ({ id, name })).sort((a, b) =>
      a.name.localeCompare(b.name)
    );
  }, [mappedAccounts, plannerAccounts]);

  const openAddActivity = (date?: Date) => {
    setActivityInitialDate(date ?? selectedDate);
    if (activityAccounts.length === 0) {
      toast({
        title: "No accounts",
        description: "Map yourself to an account before adding activities.",
        variant: "destructive",
      });
      return;
    }
    if (activityAccounts.length === 1) {
      setActivityAccountId(activityAccounts[0].id);
      setActivityWizardOpen(true);
      return;
    }
    setPickerAccountId("");
    setAccountPickerOpen(true);
  };

  const confirmAccountPicker = () => {
    if (!pickerAccountId) {
      toast({ title: "Required", description: "Select an account", variant: "destructive" });
      return;
    }
    setActivityAccountId(pickerAccountId);
    setAccountPickerOpen(false);
    setActivityWizardOpen(true);
  };

  const openNewReminder = (date?: Date) => {
    const d = date ?? selectedDate;
    setNewTask((prev) => ({
      ...prev,
      dueAt: format(d, "yyyy-MM-dd"),
      dueTime: prev.dueTime || "09:00",
    }));
    setIsCreateOpen(true);
  };

  const handleCreate = async () => {
    if (!newTask.title.trim()) {
      toast({
        title: "Error",
        description: "Title is required",
        variant: "destructive",
      });
      return;
    }

    if (!newTask.dueAt || !newTask.dueTime) {
      toast({
        title: "Error",
        description: "Due date and time are required",
        variant: "destructive",
      });
      return;
    }

    try {
      setIsCreating(true);
      const dueDateTime = new Date(`${newTask.dueAt}T${newTask.dueTime}`);
      
      await createTask({
        title: newTask.title,
        description: newTask.description || undefined,
        ownerUserId: backendUserId || "",
        leadId: newTask.leadId && newTask.leadId !== "none" ? newTask.leadId : undefined,
        dueAt: dueDateTime.toISOString(),
      });

      toast({
        title: "Success",
        description: "Reminder created",
      });
      setIsCreateOpen(false);
      setNewTask({
        title: "",
        description: "",
        leadId: "none",
        dueAt: "",
        dueTime: "",
      });
      void loadTasks();
    } catch (err) {
      toast({
        title: "Error",
        description: err instanceof Error ? err.message : "Failed to create reminder",
        variant: "destructive",
      });
    } finally {
      setIsCreating(false);
    }
  };

  const handleComplete = async (taskId: string) => {
    try {
      await updateTask(taskId, { status: "COMPLETED" });
      void loadTasks();
      toast({
        title: "Success",
        description: "Reminder marked as completed",
      });
    } catch (err) {
      toast({
        title: "Error",
        description: err instanceof Error ? err.message : "Failed to complete reminder",
        variant: "destructive",
      });
    }
  };

  const handleDelete = async () => {
    if (!deleteTaskId) return;
    try {
      await deleteTask(deleteTaskId);
      void loadTasks();
      setDeleteTaskId(null);
      toast({
        title: "Success",
        description: "Reminder deleted",
      });
    } catch (err) {
      toast({
        title: "Error",
        description: err instanceof Error ? err.message : "Failed to delete reminder",
        variant: "destructive",
      });
    }
  };

  const confirmDelete = (taskId: string) => {
    setDeleteTaskId(taskId);
  };

  const calendarItems = useMemo<CalendarItem[]>(() => {
    const items: CalendarItem[] = [
      ...activities
        .filter((activity) => activity.status !== "CANCELLED" && activity.startsAt)
        .map((activity) => ({
          kind: "activity" as const,
          date: new Date(activity.startsAt),
          activity,
        })),
      ...tasks
        .filter((task) => task.dueAt)
        .map((task) => ({
          kind: "task" as const,
          date: new Date(task.dueAt),
          task,
        })),
      ...accountFollowUps
        .filter((followUp) => followUp.followUpDate)
        .map((followUp) => ({
          kind: "account_followup" as const,
          date: new Date(followUp.followUpDate),
          followUp,
        })),
    ];
    return items.sort((a, b) => a.date.getTime() - b.date.getTime());
  }, [activities, tasks, accountFollowUps]);

  const selectedDateItems = useMemo(
    () => calendarItems.filter((item) => isSameDay(item.date, selectedDate)),
    [calendarItems, selectedDate]
  );

  const calendarDays = useMemo(() => {
    const start = startOfMonth(currentMonth);
    const end = endOfMonth(currentMonth);
    return eachDayOfInterval({ start, end });
  }, [currentMonth]);

  const getItemsForDay = (day: Date) =>
    calendarItems.filter((item) => isSameDay(item.date, day));

  const getStatusBadge = (status: string) => {
    const styles: Record<string, string> = {
      OPEN: "bg-blue-50 text-blue-600 border-blue-200",
      COMPLETED: "bg-emerald-50 text-emerald-600 border-emerald-200",
      CANCELLED: "bg-slate-100 text-slate-500 border-slate-200",
    };
    return styles[status] || styles.OPEN;
  };

  const monthStart = startOfMonth(currentMonth);
  const firstDayOfWeek = monthStart.getDay();
  const daysBeforeMonth = Array.from({ length: firstDayOfWeek }, (_, i) => null);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl font-semibold text-text">Calendar</h1>
          <p className="text-text-muted mt-1">
            Activities, follow-ups, and reminders across your accounts and leads
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <Button variant="outline" onClick={() => openAddActivity()}>
            <Plus className="h-4 w-4 mr-2" />
            Add activity
          </Button>
          <Button
            onClick={() => openNewReminder()}
            className="bg-slate-900 hover:bg-slate-800 text-white"
          >
            <Plus className="h-4 w-4 mr-2" />
            New Reminder
          </Button>
        </div>
      </div>

      {/* Calendar and Tasks */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Calendar */}
        <Card className="lg:col-span-1 border-slate-200 shadow-sm">
          <CardContent className="p-6">
            <div className="flex items-center justify-between mb-4">
              <h3 className="font-semibold text-slate-900">Calendar</h3>
              <div className="flex items-center gap-2">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => {
                    const prevMonth = new Date(currentMonth);
                    prevMonth.setMonth(prevMonth.getMonth() - 1);
                    setCurrentMonth(prevMonth);
                  }}
                >
                  ‹
                </Button>
                <span className="text-sm font-medium text-slate-700 min-w-[100px] text-center">
                  {format(currentMonth, "MMMM yyyy")}
                </span>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => {
                    const nextMonth = new Date(currentMonth);
                    nextMonth.setMonth(nextMonth.getMonth() + 1);
                    setCurrentMonth(nextMonth);
                  }}
                >
                  ›
                </Button>
              </div>
            </div>

            {/* Calendar Grid */}
            <div className="overflow-x-auto max-w-full -mx-1 px-1">
              <div className="min-w-0">
                <div className="grid grid-cols-7 gap-0.5 sm:gap-1 mb-2">
                  {["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day) => (
                    <div key={day} className="text-[10px] sm:text-xs font-semibold text-slate-500 text-center py-1 sm:py-2">
                      {day.slice(0, 1)}
                      <span className="hidden sm:inline">{day.slice(1)}</span>
                    </div>
                  ))}
                </div>

                <div className="grid grid-cols-7 gap-0.5 sm:gap-1">
                  {daysBeforeMonth.map((_, idx) => (
                    <div key={`empty-${idx}`} className="aspect-square" />
                  ))}
                  {calendarDays.map((day) => {
                    const dayItems = getItemsForDay(day);
                    const isSelected = isSameDay(day, selectedDate);
                    const isTodayDate = isToday(day);

                    return (
                      <button
                        key={day.toISOString()}
                        onClick={() => setSelectedDate(day)}
                        className={`aspect-square rounded-sm text-xs sm:text-sm transition-colors ${
                          isSelected
                            ? "bg-slate-900 text-white"
                            : isTodayDate
                            ? "bg-emerald-50 text-emerald-600 font-semibold"
                            : "hover:bg-slate-50 text-slate-700"
                        }`}
                      >
                        <div className="flex flex-col items-center justify-center h-full">
                          <span>{format(day, "d")}</span>
                          {dayItems.length > 0 && (
                            <span
                              className={`text-[10px] mt-0.5 ${
                                isSelected ? "text-white" : "text-emerald-600"
                              }`}
                            >
                              ●
                            </span>
                          )}
                        </div>
                      </button>
                    );
                  })}
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Calendar items for selected date */}
        <Card className="lg:col-span-2 border-slate-200 shadow-sm">
          <CardContent className="p-6">
            <div className="flex items-center justify-between mb-4 gap-2">
              <h3 className="font-semibold text-slate-900">
                {format(selectedDate, "EEEE, MMMM d, yyyy")}
              </h3>
              <div className="flex flex-wrap gap-2">
                <Button size="sm" variant="outline" onClick={() => openAddActivity(selectedDate)}>
                  <Plus className="h-4 w-4 mr-1" />
                  Activity
                </Button>
                <Button size="sm" variant="outline" onClick={() => openNewReminder(selectedDate)}>
                  <Plus className="h-4 w-4 mr-1" />
                  Reminder
                </Button>
              </div>
            </div>

            {isLoading ? (
              <div className="flex items-center justify-center py-12">
                <Loader2 className="h-8 w-8 animate-spin text-slate-400" />
              </div>
            ) : selectedDateItems.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-12">
                <CalendarIcon className="h-12 w-12 text-slate-300 mb-4" />
                <p className="text-slate-500">No calendar items for this date</p>
                <div className="mt-4 flex gap-2">
                  <Button size="sm" onClick={() => openAddActivity(selectedDate)}>
                    Add activity
                  </Button>
                  <Button size="sm" variant="outline" onClick={() => openNewReminder(selectedDate)}>
                    New reminder
                  </Button>
                </div>
              </div>
            ) : (
              <div className="divide-y divide-border rounded-md border border-border">
                {selectedDateItems.map((item) => {
                  if (item.kind === "activity") {
                    const activity = item.activity;
                    return (
                      <div key={`activity-${activity._id}`} className="p-4">
                        <div className="flex flex-wrap items-start justify-between gap-3">
                          <div>
                            <div className="flex flex-wrap items-center gap-2">
                              <p className="font-medium text-text">
                                {formatContactActivityType(activity.activityType)}
                              </p>
                              <Badge variant="outline">Activity</Badge>
                            </div>
                            <p className="mt-1 text-sm text-text-muted">
                              {format(item.date, "h:mm a")}
                              {activity.endsAt
                                ? ` – ${format(new Date(activity.endsAt), "h:mm a")}`
                                : ""}
                            </p>
                            <p className="mt-1 text-sm text-text-muted">
                              {[activity.accountId?.name, activity.contactId?.name]
                                .filter(Boolean)
                                .join(" · ")}
                            </p>
                          </div>
                          <div className="flex gap-2">
                            {activity.accountId?._id && onViewAccount && (
                              <Button
                                size="sm"
                                variant="ghost"
                                onClick={() => onViewAccount(activity.accountId!._id)}
                              >
                                Account
                              </Button>
                            )}
                            {activity.leadId?._id && onViewLead && (
                              <Button
                                size="sm"
                                variant="ghost"
                                onClick={() => onViewLead(activity.leadId!._id)}
                              >
                                Lead
                              </Button>
                            )}
                          </div>
                        </div>
                      </div>
                    );
                  }

                  if (item.kind === "account_followup") {
                    return (
                      <div key={`followup-${item.followUp._id}`} className="p-4">
                        <div className="flex flex-wrap items-start justify-between gap-3">
                          <div>
                            <div className="flex flex-wrap items-center gap-2">
                              <p className="font-medium text-text">
                                Follow-up: {item.followUp.name}
                              </p>
                              <Badge variant="outline">Account follow-up</Badge>
                            </div>
                            <p className="mt-1 text-sm text-text-muted">
                              {item.followUp.followUpNote || "No follow-up note"}
                            </p>
                          </div>
                          {onViewAccount && (
                            <Button
                              size="sm"
                              variant="ghost"
                              onClick={() => onViewAccount(item.followUp._id)}
                            >
                              Account
                            </Button>
                          )}
                        </div>
                      </div>
                    );
                  }

                  const task = item.task;
                  const isCompleted = task.status === "COMPLETED";
                  const leadId = task.lead?.id || task.leadId;
                  return (
                    <div
                      key={`task-${task.id}`}
                      className={`p-4 ${isCompleted ? "opacity-60" : ""}`}
                    >
                      <div className="flex flex-wrap items-start justify-between gap-3">
                        <div>
                          <div className="flex flex-wrap items-center gap-2">
                            <p className={isCompleted ? "font-medium line-through" : "font-medium"}>
                              {task.title}
                            </p>
                            <Badge
                              variant="outline"
                              className={getStatusBadge(task.status)}
                            >
                              {task.type === "followup" ? "Follow-up" : "Task"}
                            </Badge>
                          </div>
                          <p className="mt-1 text-sm text-text-muted">
                            {format(item.date, "h:mm a")}
                            {task.description ? ` · ${task.description}` : ""}
                          </p>
                          {task.lead && (
                            <p className="mt-1 text-sm text-text-muted">
                              Lead {task.lead.leadNumber || task.lead.id}
                            </p>
                          )}
                        </div>
                        <div className="flex gap-2">
                          {!isCompleted && (
                            <Button
                              size="sm"
                              variant="outline"
                              onClick={() => handleComplete(task.id)}
                            >
                              <CheckCircle2 className="mr-1 h-3 w-3" />
                              Complete
                            </Button>
                          )}
                          {leadId && onViewLead && (
                            <Button
                              size="sm"
                              variant="ghost"
                              onClick={() => onViewLead(leadId)}
                              title="View lead"
                            >
                              <ExternalLink className="h-3 w-3" />
                            </Button>
                          )}
                          <Button
                            size="sm"
                            variant="ghost"
                            onClick={() => confirmDelete(task.id)}
                            title="Delete reminder"
                          >
                            <X className="h-3 w-3" />
                          </Button>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      {/* Create Reminder Dialog */}
      <Dialog open={isCreateOpen} onOpenChange={setIsCreateOpen}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>New Reminder</DialogTitle>
            <DialogDescription>
              Create a new reminder for follow-ups or tasks
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div>
              <Label className="text-sm font-semibold text-slate-600 mb-2 block">Title *</Label>
              <Input
                placeholder="Follow up with guest..."
                value={newTask.title}
                onChange={(e) => setNewTask({ ...newTask, title: e.target.value })}
                className="border-slate-200"
              />
            </div>
            <div>
              <Label className="text-sm font-semibold text-slate-600 mb-2 block">Lead ID</Label>
              <Select
                value={newTask.leadId}
                onValueChange={(value) => setNewTask({ ...newTask, leadId: value })}
              >
                <SelectTrigger className="border-slate-200">
                  <SelectValue placeholder="Optional" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="none">None</SelectItem>
                  {leads
                    .filter((lead) => lead.id && typeof lead.id === "string" && lead.id.trim() !== "")
                    .map((lead, index) => {
                      const leadId = String(lead.id);
                      const { name } = getLeadContactInfo(lead);
                      const displayName = name || `Lead #${lead.leadNumber || lead.id}`;
                      return (
                        <SelectItem key={`${leadId}-${index}`} value={leadId}>
                          {displayName}
                        </SelectItem>
                      );
                    })}
                </SelectContent>
              </Select>
            </div>
            <div className={formGrid2}>
              <div>
                <Label className="text-sm font-semibold text-slate-600 mb-2 block">Due Date *</Label>
                <Input
                  type="date"
                  value={newTask.dueAt}
                  onChange={(e) => setNewTask({ ...newTask, dueAt: e.target.value })}
                  className="border-slate-200"
                />
              </div>
                <div>
                <Label className="text-sm font-semibold text-slate-600 mb-2 block">Due Time *</Label>
                <Input
                  type="time"
                  value={newTask.dueTime}
                  onChange={(e) => setNewTask({ ...newTask, dueTime: e.target.value })}
                  className="border-slate-200"
                />
              </div>
            </div>
            <div>
              <Label className="text-sm font-semibold text-slate-600 mb-2 block">Description</Label>
              <Textarea
                placeholder="Additional notes..."
                value={newTask.description}
                onChange={(e) => setNewTask({ ...newTask, description: e.target.value })}
                className="border-slate-200 min-h-[100px]"
              />
            </div>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsCreateOpen(false)}
              className="border-slate-200"
            >
              Cancel
            </Button>
            <Button
              onClick={handleCreate}
              disabled={isCreating}
              className="bg-emerald-600 hover:bg-emerald-700 text-white"
            >
              {isCreating ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Creating...
                </>
              ) : (
                <>
                  <Plus className="h-4 w-4 mr-2" />
                  Create Reminder
                </>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <AlertDialog open={!!deleteTaskId} onOpenChange={(open) => !open && setDeleteTaskId(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Reminder</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete this reminder? This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel onClick={() => setDeleteTaskId(null)}>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleDelete}
              className="bg-red-600 hover:bg-red-700 text-white"
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      <Dialog open={accountPickerOpen} onOpenChange={setAccountPickerOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Select account</DialogTitle>
          </DialogHeader>
          <div className="space-y-2">
            <Label>Activity for account</Label>
            <Select value={pickerAccountId} onValueChange={setPickerAccountId}>
              <SelectTrigger>
                <SelectValue placeholder="Choose account" />
              </SelectTrigger>
              <SelectContent>
                {activityAccounts.map((a) => (
                  <SelectItem key={a.id} value={a.id}>
                    {a.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setAccountPickerOpen(false)}>
              Cancel
            </Button>
            <Button onClick={confirmAccountPicker}>Continue</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {activityAccountId && (
        <ActivityWizard
          open={activityWizardOpen}
          onOpenChange={(open) => {
            setActivityWizardOpen(open);
            if (!open) setActivityAccountId(null);
          }}
          accountId={activityAccountId}
          initialDate={activityInitialDate}
          onSuccess={() => {
            setActivityWizardOpen(false);
            setActivityAccountId(null);
            void loadTasks();
          }}
        />
      )}
    </div>
  );
};

export default PersonalCalendar;
