import { API_BASE_URL, withAuthHeaders } from "./api";

export type TaskStatus = "OPEN" | "COMPLETED" | "CANCELLED";
export type TaskType =
  | "general"
  | "followup"
  | "call"
  | "email"
  | "whatsapp"
  | "meeting";

export interface Task {
  id: string;
  title: string;
  description?: string;
  ownerUserId: string;
  createdByUserId?: string;
  leadId?: string;
  orgId?: string;
  dueAt: string;
  status: TaskStatus;
  type: TaskType;
  isAutoGenerated: boolean;
  completedAt?: string;
  outcome?: string;
  completedByUserId?: string | { _id: string; name: string };
  popupState?: {
    lastShownAt?: string;
    dismissedAt?: string;
    workflowFollowupMissedEmittedAt?: string;
  };
  createdAt?: string;
  updatedAt?: string;
  // Populated fields
  ownerUser?: {
    id: string;
    name: string;
    email: string;
  };
  createdByUser?: {
    id: string;
    name: string;
    email: string;
  };
  lead?: {
    id: string;
    leadNumber: string;
    status: string;
  };
}

export interface TaskListQuery {
  ownerUserId?: string;
  leadId?: string;
  status?: TaskStatus;
  fromDue?: string;
  toDue?: string;
}

export interface CreateTaskPayload {
  title: string;
  description?: string;
  ownerUserId: string;
  leadId?: string;
  dueAt: string;
  type?: TaskType;
}

export interface UpdateTaskPayload {
  title?: string;
  description?: string;
  status?: TaskStatus;
  outcome?: string;
  completedAt?: string;
  completedByUserId?: string;
}

/**
 * List tasks with optional filters
 */
export const listTasks = async (query?: TaskListQuery): Promise<Task[]> => {
  const params = new URLSearchParams();
  if (query) {
    Object.entries(query).forEach(([key, value]) => {
      if (value) params.append(key, value);
    });
  }

  const url =
    `${API_BASE_URL}/tasks` +
    (params.toString() ? `?${params.toString()}` : "");

  const response = await fetch(url, {
    headers: withAuthHeaders(),
  });

  if (!response.ok) {
    let message = "Unable to fetch tasks";
    try {
      const data = await response.json();
      if (data?.message) message = data.message;
    } catch {
      // ignore
    }
    throw new Error(message);
  }

  const raw = (await response.json()) as any[];
  return mapTasks(raw);
};

/** List tasks for a specific lead (user must have lead access) */
export const listTasksForLead = (leadId: string): Promise<Task[]> =>
  listTasks({ leadId });

function mapTasks(raw: any[]): Task[] {
  return raw.map((t) => {
    const { _id, id, leadId, ...rest } = t;
    const task: Task = {
      id: id ?? _id,
      ...rest,
    };
    // Map populated leadId to lead field
    if (leadId && typeof leadId === "object" && leadId._id) {
      task.lead = {
        id: leadId._id || leadId.id,
        leadNumber: leadId.leadNumber || "",
        status: leadId.status || "",
      };
      task.leadId = leadId._id || leadId.id;
    } else if (leadId) {
      task.leadId = leadId;
    }
    return task;
  });
};

/**
 * Create a new task/follow-up reminder
 */
export const createTask = async (payload: CreateTaskPayload): Promise<Task> => {
  const response = await fetch(`${API_BASE_URL}/tasks`, {
    method: "POST",
    headers: withAuthHeaders({
      "Content-Type": "application/json",
    }),
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    let message = "Unable to create task";
    try {
      const data = await response.json();
      if (data?.message) message = data.message;
    } catch {
      // ignore
    }
    throw new Error(message);
  }

  const raw = (await response.json()) as any;
  const { _id, id, leadId, ...rest } = raw;
  const task: Task = {
    id: id ?? _id,
    ...rest,
  };
  // Map populated leadId to lead field
  if (leadId && typeof leadId === "object" && leadId._id) {
    task.lead = {
      id: leadId._id || leadId.id,
      leadNumber: leadId.leadNumber || "",
      status: leadId.status || "",
    };
    task.leadId = leadId._id || leadId.id;
  } else if (leadId) {
    task.leadId = leadId;
  }
  return task;
};

/**
 * Update a task (only owner can update)
 */
export const updateTask = async (
  taskId: string,
  payload: UpdateTaskPayload
): Promise<Task> => {
  const response = await fetch(`${API_BASE_URL}/tasks/${taskId}`, {
    method: "PATCH",
    headers: withAuthHeaders({
      "Content-Type": "application/json",
    }),
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    let message = "Unable to update task";
    try {
      const data = await response.json();
      if (data?.message) message = data.message;
    } catch {
      // ignore
    }
    throw new Error(message);
  }

  const raw = (await response.json()) as any;
  const { _id, id, leadId, ...rest } = raw;
  const task: Task = {
    id: id ?? _id,
    ...rest,
  };
  // Map populated leadId to lead field
  if (leadId && typeof leadId === "object" && leadId._id) {
    task.lead = {
      id: leadId._id || leadId.id,
      leadNumber: leadId.leadNumber || "",
      status: leadId.status || "",
    };
    task.leadId = leadId._id || leadId.id;
  } else if (leadId) {
    task.leadId = leadId;
  }
  return task;
};

/**
 * Delete a task (only owner can delete)
 */
export const deleteTask = async (taskId: string): Promise<void> => {
  const response = await fetch(`${API_BASE_URL}/tasks/${taskId}`, {
    method: "DELETE",
    headers: withAuthHeaders(),
  });

  if (!response.ok) {
    let message = "Unable to delete task";
    try {
      const data = await response.json();
      if (data?.message) message = data.message;
    } catch {
      // ignore
    }
    throw new Error(message);
  }
};

/**
 * Get today's follow-ups for the current user
 */
export const getTodaysFollowUps = async (): Promise<Task[]> => {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const tomorrow = new Date(today);
  tomorrow.setDate(tomorrow.getDate() + 1);

  return listTasks({
    status: "OPEN",
    fromDue: today.toISOString(),
    toDue: tomorrow.toISOString(),
  });
};

/**
 * Get overdue follow-ups for the current user
 */
export const getOverdueFollowUps = async (): Promise<Task[]> => {
  const now = new Date();
  now.setHours(0, 0, 0, 0);

  const tasks = await listTasks({
    status: "OPEN",
    toDue: now.toISOString(),
  });

  // Filter to get only truly overdue (before today)
  return tasks.filter((task) => new Date(task.dueAt) < now);
};

/**
 * Get upcoming follow-ups for the current user (next 7 days)
 */
export const getUpcomingFollowUps = async (): Promise<Task[]> => {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const weekFromNow = new Date(today);
  weekFromNow.setDate(weekFromNow.getDate() + 7);

  return listTasks({
    status: "OPEN",
    fromDue: today.toISOString(),
    toDue: weekFromNow.toISOString(),
  });
};

/**
 * Dismiss a task popup (snooze for now)
 */
export const dismissTaskPopup = async (taskId: string): Promise<Task> => {
  const response = await fetch(`${API_BASE_URL}/tasks/${taskId}/dismiss`, {
    method: "POST",
    headers: withAuthHeaders(),
  });

  if (!response.ok) {
    let message = "Unable to dismiss task";
    try {
      const data = await response.json();
      if (data?.message) message = data.message;
    } catch {
      // ignore
    }
    throw new Error(message);
  }

  const raw = (await response.json()) as any;
  const { _id, id, leadId, ...rest } = raw;
  const task: Task = {
    id: id ?? _id,
    ...rest,
  };
  // Map populated leadId to lead field
  if (leadId && typeof leadId === "object" && leadId._id) {
    task.lead = {
      id: leadId._id || leadId.id,
      leadNumber: leadId.leadNumber || "",
      status: leadId.status || "",
    };
    task.leadId = leadId._id || leadId.id;
  } else if (leadId) {
    task.leadId = leadId;
  }
  return task;
};

export const getTaskSummary = async (): Promise<{
  overdue: number;
  dueToday: number;
  upcoming: number;
  completedToday: number;
}> => {
  const response = await fetch(`${API_BASE_URL}/tasks/summary`, {
    headers: withAuthHeaders(),
  });

  if (!response.ok) {
    let message = "Unable to fetch task summary";
    try {
      const data = await response.json();
      if (data?.message) message = data.message;
    } catch {
      // ignore
    }
    throw new Error(message);
  }

  return response.json();
};

